---
# handlers file for ansible-role-nginx

- name: restart nginx
  service: name=nginx state=restarted
  when: not nginx_first_start.changed

- name: reload nginx
  service: name=nginx state=reloaded